site_name: PHP Chess
site_url: https://php-chess.chesslablab.org/php-chess/
theme:
  name: mkdocs
nav:
  - Getting Started: getting-started.md
  - Format Converters: format-converters.md
  - Heuristics: heuristics.md
  - Chess Tutor: chess-tutor.md
  - Play Chess: play-chess.md
