site_name: PHP Chess
pages:
  - Chess\Game: index.md
  - Chess\Grandmaster: grandmaster.md
  - Chess\Heuristics: heuristics.md
  - Chess\Movetext: movetext.md
  - Chess\Media\BoardToMp4: media-board-to-mp4.md
  - Chess\Media\BoardToPng: media-board-to-png.md
  - Chess\Player\LanPlayer: player-lan-player.md
  - Chess\Player\PgnPlayer: player-pgn-player.md
  - Chess\UciEngine\Stockfish: uciengine-stockfish.md
  - Chess\Variant\Classical\Board: variant-classical-board.md
  - Chess\Variant\Classical\Randomizer\Checkmate\TwoBishopsRandomizer: variant-classical-randomizer-checkmate-two-bishops-randomizer.md
  - Chess\Variant\Classical\Randomizer\Endgame\PawnEndgameRandomizer: variant-classical-randomizer-endgame-pawn-endgame-randomizer.md
  - Chess\Variant\Classical\Randomizer\Randomizer: variant-classical-randomizer-randomizer.md
  - Command Line Interface: cli.md
theme: readthedocs
